language: node_js
node_js:
- '12'
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: wfh-backend
  api_key:
    secure: E9KkDRowj3vEmBgnfABLhkYLDD8JyHCV5HcpZw6qM34wMErcah3C+nC43lm7TDSCRfqsDMIXRFfg9j1J2yG3ITHEX9zYxbDfsVOYEML3B5qMRYASrKn9tMzWpA4RQj+8RBeH9AtzPGFBvDqBuXVm+9NwlLTTrw9+glZA4VjMT2dQRH9N4hAg296/5Qv89xKkVcpy4iRgVypF+x6LYPMVmJw32cgMopivBDpSgSHzdMzTzwVueyV2WWIflMwxNzlAMdwY1CzlLv1J5iRGZrvmg1vN6UGOjYreCy3t63GiZI2vld/eKHEwoaM/pCIwGCI+TrzRQdS6Tg8jHUcA5eFHwKEyaKyNT9SQQq63FI57b7fkfSrXzOb31zNG1ggDKDRwIe5qEQ9n1uDK795rwtzi+Udt752H7ETc+DSv9WFgEutoDZOEMeXcOJNj5HuunfdZ8nE9oBvAUi0p4S9qbtWgThkFVm4z/e5XTUsgGiNPFk+3CbnbJWT3qOOKAJ39vTbetTtYTDgjFBxoT3yY2LPlJ+WhMOAnebajdHoXCPcLS02T4ayi/vOXluEN00U9VBGWzKTC9fQ7hFDhZok90vyaufhXSq+edA66Lu+sbejICuL+o8vywyhfSb6tLQwprIM9Xlg3A4vhe/M1VEdSCM/mTdCpQTJR2HLmgKucPBRJkgU=
